format = """
[](#ebcb8b)\
$username\
[](bg:#d8dee9 fg:#ebcb8b)\
$directory\
[](fg:#9C59D1 bg:#2e3440)\
[](fg:#2e3440)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#ebcb8b"
format = '[🐼]($style)'

[directory]
style = "bg:#d8dee9 fg:#b48ead bold"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"
